Terraform 2
Otus-DevOps-2021-11/JakUi_infra pull request #8
Opened 2022-01-14 09:53 UTC by JakUi

# Выполнено ДЗ №

 - [X] Основное ДЗ
 - [1/2 ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Задание со *, но не с**

## Как проверить работоспособность:
 - Смотрите readme.md

## PR checklist
 - [X] Выставил label с номером домашнего задания
 - [X] Выставил label с темой домашнего задания

2022-01-14 10:10 UTC, JakUi commented
С тестами нужна помощь: я вообще не понимаю что им не нравится...

2022-01-14 13:59 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Оставил комментарий к файлу, кажется что там не сильно много правок =)
ДЗ возвращаю на доработку

2022-01-14 13:59 UTC, mrgreyves commented on terraform/prod/backend.tf
> +    yandex = {}
Нужно пофиксить описание провайдера
Больше часть проблем на данный момент из-за этого

2022-01-14 15:22 UTC, JakUi commented on terraform/prod/backend.tf
> +    yandex = {}
Прикольно) Я его удалил т.к. terraform в консоли выдавал предупреждение. Попробую

2022-01-14 15:30 UTC, JakUi commented
Поправил описание провайдера в бекэнде, тесты всё равно падают)

2022-01-16 15:22 UTC, mrgreyves requested changes
Здравствуйте!)
Там чуть-чуть поправить надо провайдера =)

2022-01-16 15:22 UTC, mrgreyves commented on terraform/prod/backend.tf
> +  }
Тут лишняя скобка =)

2022-01-17 07:08 UTC, JakUi commented on terraform/prod/backend.tf
> +  }
Точно

2022-01-17 07:50 UTC, JakUi commented on terraform/prod/backend.tf
> +  }
Не согласен (в доках яндекса было именно так, но видимо я ещё плохо в этом разбираюсь)). Пофиксил, тесты проходят. Спасибо за помощь

2022-01-18 08:35 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь апрув =)

2022-01-18 08:37 UTC, merged